import Footer from "@/components/Footer";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Converse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-4">{children}</body>
    </html>
  );
}
