import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { ModalProvider } from '@/contexts/modal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Converse',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <ModalProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ModalProvider>
    </ClerkProvider>
  );
}
